{% set version = "1.2.0" %}

package:
  name: randomfiletree
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/r/randomfiletree/RandomFileTree-{{ version }}.tar.gz
    sha256: 3a92e12ecbf093dc6b3fc1405c69030ed32db3a8a4a71f28724bd347f4c49afc
    patches:
      - 0000-setuptools.patch
  - url: https://raw.githubusercontent.com/klieret/RandomFileTree/v1.2.0/LICENSE.txt
    sha256: 4da4a2f04603fcd10ee2868810e9863c0a55165f42a969bd8c31b42ec7e058f7

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -c '__import__("shutil").rmtree(__import__("pathlib").Path("randomfiletree/bin"))'
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - randomfiletree = randomfiletree.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - randomfiletree
  commands:
    - pip check
    - randomfiletree --help
    - coverage run --source=randomfiletree --branch -m pytest -vv --color=yes --tb=long --pyargs randomfiletree 
    - coverage report --show-missing --skip-covered --fail-under=96

about:
  home: https://github.com/klieret/RandomFileTree
  summary: Create a random file/directory tree/structure in python for testing purposes.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://randomfiletree.readthedocs.io
  doc_source_url: https://github.com/klieret/RandomFileTree/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - bollwyvl
